packages:
  - apps/*
  - packages/*
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  cpu-features: false
  esbuild: true
  protobufjs: false
  sharp: false
  ssh2: false
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.5'
  - '@turbo/darwin-arm64@2.11.5'
  - '@turbo/linux-64@2.11.5'
  - '@turbo/linux-arm64@2.11.5'
  - '@turbo/windows-64@2.11.5'
  - '@turbo/windows-arm64@2.11.5'
  - turbo@2.11.5
  - '@testcontainers/postgresql@12.2.0'
  - testcontainers@12.2.0
  - '@nestjs/common@12.1.1'
  - '@nestjs/core@12.1.1'
  - '@nestjs/platform-express@12.1.1'
  - '@nestjs/testing@12.1.1'
  - '@testcontainers/rabbitmq@12.2.0'
  - '@testcontainers/valkey@12.2.0'
  - amqplib@2.2.0
onlyBuiltDependencies:
  - sharp
  - '@tailwindcss/oxide'

