import { drizzle, type NodePgDatabase } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import pg from "pg";

export type Database<
  TSchema extends Record<string, unknown> = Record<string, never>,
> = NodePgDatabase<TSchema>;

/** Any Drizzle handle that can run queries: the database or a transaction. */
export type Executor = Pick<
  NodePgDatabase<Record<string, unknown>>,
  "execute" | "insert" | "select" | "update" | "delete"
>;

export type DatabaseOptions<TSchema extends Record<string, unknown>> = {
  url: string;
  schema?: TSchema;
  /** Pool size; one VPS, so keep it small (default 10). */
  max?: number;
  applicationName?: string;
  /** An idle connection was lost (restart, failover, network); the pool reconnects on next use. */
  onIdleError?: (error: Error) => void;
};

export function createDatabase<TSchema extends Record<string, unknown>>(
  options: DatabaseOptions<TSchema>,
) {
  const pool = new pg.Pool({
    connectionString: options.url,
    max: options.max ?? 10,
    application_name: options.applicationName,
    idleTimeoutMillis: 30_000,
    connectionTimeoutMillis: 5_000,
  });
  // Without a listener, pg re-throws an idle client's error and the process
  // dies, e.g. on every PostgreSQL restart (node-postgres Pool docs).
  pool.on("error", (error) => options.onIdleError?.(error));
  const db = drizzle({
    client: pool,
    ...(options.schema ? { schema: options.schema } : {}),
  }) as NodePgDatabase<TSchema>;
  return {
    db,
    pool,
    /** Lightweight readiness probe. */
    ping: async () => {
      await pool.query("select 1");
    },
    close: () => pool.end(),
  };
}

/**
 * Applies SQL migrations generated by drizzle-kit, over a single dedicated
 * connection as Drizzle recommends for DDL.
 */
export async function runMigrations(url: string, migrationsFolder: string) {
  const client = new pg.Client({ connectionString: url });
  await client.connect();
  try {
    await migrate(drizzle({ client }), { migrationsFolder });
  } finally {
    await client.end();
  }
}
